version: '3.8'

networks:
  jenkins-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/jenkinshome/:/data/db
    networks:
      - jenkins-network
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: Jenkins
      MONGO_INITDB_ROOT_PASSWORD: admin123

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkinsconf:/var/jenkins_home
    networks:
      - jenkins-network
    expose:
      - "8080"
    user: root
    restart: unless-stopped
    command: >
      bash -c "apt-get update &&
               apt-get install -y vim nano &&
               exec /usr/bin/tini -- /usr/local/bin/jenkins.sh"
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Jenkins
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - jenkins-network
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Jenkins
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8082:8081"
    volumes:
      - nexus:/nexus-data
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkinsconf:
  mongodata:
  nexus:
